.TH MKPW 8
.SH NAME
mkpw \- generate safe passwords
.SH SYNOPSIS
.B mkpw
[\fB\-l\fR \fILENGHT\fR]
|\fB\-\-exclude\fR \fICHARS\fR]
|\fB\-\-exclude\-ambigious\fR]
|\fB\-\-exclude\-lowercase\fR]
|\fB\-\-exclude\-uppercase\fR]
|\fB\-\-exclude\-digits\fR]
|\fB\-\-exclude\-special\fR]
|\fB\-\-choices\fR \fICHARS\fR]
[\fICOUNT\fR]
.SH DESCRIPTION
.B mkpw
is small tool that can generate safe passwords and take individual characteristics into account.
It has resonable default values that ensure strong passwords.  The behaviour can be changed by
using command line arguments and configuration files.
.SH OPTIONS
.TP
.BR \-l ", " \-\-length =\fILENGTH\fR
Length of passwords to be generated. Default is 16.
.TP
.BR \-\-exclude =\fCHARS\fR
Exclude given characters from choices for password creation.
.TP
.BR \-\-exclude\-ambigious
Exclude ambigious characters from choices for password creation.  This usually includes characters that look similar to others.  Since the confusion can raise problems, these characters are removed.  This option is enabled by default.
.TP
.BR \-\-exclude\-lowercase
Exclude lowercase characters from choices for password creation.
.TP
.BR \-\-exclude\-uppercase
Exclude uppercase characters from choices for password creation.
.TP
.BR \-\-exclude\-digits
Exclude digits from choices for password creation.
.TP
.BR \-\-exclude\-special
Exclude special characters from choices for password creation.
.TP
.BR \-\-choices =\fICHARS\fR
Use the given characters instead of the character classes.
.SH FILES
/etc/mkpw.cfg
.TP
/usr/local/etc/mkpw.cfg
.TP
~/.mkpw.cfg
.SH BUGS
If you experience bugs or want to provide feedback, please visit the project page on GitHub:
\fIhttps://github.com/commx/mkpw\fR
.SH AUTHOR
Christian Kroeger <commx@commx.ws>
